name: Auto compile

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/auto-compile.yaml"
      - "crates/*/src/**"
      - "crates/*/Cargo.toml"
      - "Cargo.toml"
      - "Cargo.lock"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: aarch64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install musl-tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get install -y musl-tools

      - name: Install Zig (For Linux ARM cross-compile)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        uses: mlugg/setup-zig@v2
        with:
          version: latest

      - name: Install cargo-zigbuild
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: cargo install cargo-zigbuild

      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]; then
            cargo zigbuild -r --target ${{ matrix.target }} --workspace
          else
            cargo b -r --target ${{ matrix.target }} --workspace
          fi

      - name: Upload Binaries
        uses: actions/upload-artifact@v7
        with:
          name: bin-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/*.exe
            target/${{ matrix.target }}/release/rs-clip-bridge-client
            target/${{ matrix.target }}/release/rs-clip-bridge-server
            !target/${{ matrix.target }}/release/*.d
            !target/${{ matrix.target }}/release/deps/
          overwrite: true
          retention-days: 3
